[package]
name = "bevy_gst_video"
version = "0.1.1"
edition = "2021"

[dependencies]
bevy = "0.14"
gstreamer = "0.23"
gstreamer-video = "0.23"
gstreamer-app = "0.23"
gstreamer-audio = "0.23"
image = "0.25"
rodio = "0.19"
byteorder = "1.5"